source("R/00_globals.R",  local=TRUE)
source("R/01_read_area.R",local=TRUE)
source("R/02_osm_lines.R",local=TRUE)
source("R/03_layers_raw.R",local=TRUE)
source("R/04_roads_graph.R",local=TRUE)
source("R/05_snap_points.R",local=TRUE)
source("R/06_build_graphs.R",local=TRUE)
source("R/07_dependencies.R",local=TRUE)
source("R/08_cascade.R",local=TRUE)
source("R/09_metrics.R",local=TRUE)
source("R/10_visualise.R",local=TRUE)

print(plot_failure_map(target_area, points_sf, failed_all))